name: Stargate
main: org.sgrewritten.stargate.Stargate
version: @version@
description: The original, and still the best, transportation plugin for the Bukkit Ecosystem.
authors: [ Knarvik, Thorin, sgrewritten.org/credits ]
website: https://sgrewritten.org
api-version: 1.20
folia-supported: true
softdepend: [Vault, BKCommonLib, BlockUtil]
commands:
  stargate:
    description: Used to interact with the Stargate plugin at a system level.
    usage: |
      /<command> - Prints the version of Stargate the server is running.
      /<command> about - Provides a link to Stargate's documentation.
      /<command> reload - Used to reload the plugin.
      /<command> trace - Saves all data to a file, to be used for developer debugging
      /<command> version - Prints the version of Stargate the server is running.
    aliases: [ sg ]
permissions:
  sg:
    children:

      sg.info:
        default: true
        description: A group of nodes that relate to the /sg command (used for displaying info about the plugin).
        children:
          sg.info.version:
            description: Displays the plugin's version in chat. (/sg version)
          sg.info.help:
            description: Provides a link to the plugin's documentation. (/sg help)

      sg.admin:
        description: A group of nodes for permissions that are generally only applicable to staff and admins.
        default: op
        children:
          sg.admin.reload:
            description: Reloads the plugin's config.yml (/sg reload)
          sg.admin.trace:
            description: Dumps all data about this instance into a file (/sg trace)
          sg.admin.bypass:
            description: Bypasses restricted portal aspects.
            children:
              sg.admin.bypass.private:
                description: Can see and use others' private (P) gates.
              sg.admin.bypass.hidden:
                description: Can see hidden gates on a network.
              sg.admin.bypass.gatelimit:
                description: Can bypass the networkLimit specified in the config.
              #Note: the gate-limit meta can be used to specify a per-player/per-group network limit.
              sg.admin.bypass.cost:
                description: Can bypass any and all costs specified in the config.
                children:
                  sg.admin.bypass.cost.destroy:
                    description: Bypass the cost associated with destroying a portal.
                  sg.admin.bypass.cost.create:
                    description: Bypass the cost associated with creating a portal.
                  sg.admin.bypass.cost.use:
                    description: Bypass the cost associated with using a portal.

      sg.use:
        default: true
        description: Can use any portal (still can not see hidden (H) gates and can not use other users' private (P) gates).
        children:
          sg.use.follow:
            description: Even if they would otherwise lack perms, users can use any gate that has been opened by a player with the perms needed to do so.
          sg.use.world:
            description: Can use portals, regardless of the dimension within which they exit.
          #sg.use.world.<NAME> is a sub-node that allows for portals that exit in a specified dimension to be used.
          sg.use.network:
            description: Can use portals, regardless of their network.
            children:
              sg.use.network.custom:
                description: Can use portals if they are on any custom network.
              #sg.use.network.custom.<NAME> is a sub-node that allows for portals on a specific (specified) custom network to be used.
              sg.use.network.personal:
                children:
                  sg.use.network.personal.own:
                    default: true
                    description: Can use portals if they are on one's personal (username) network.
                  sg.use.network.personal.other:
                    default: op
                    description: Can use portals if they are on anothers personal (username) network.
              sg.use.network.default:
                description: Can use portals if they are on the default (central) network.
          sg.use.type:
            description: Can use all portals, regardless of type (flags).
            children:
              sg.use.type.a:
                description: Can use always-on gates.
              sg.use.type.b:
                description: Can use backwards-facing gates.
              sg.use.type.f:
                description: Can use free gates.
              sg.use.type.h:
                description: Can use hidden gates.
              sg.use.type.i:
                description: Can use modern inter-server gates.
              sg.use.type.n:
                description: Can use hidden-network gates.
              #NOT IMPL.    sg.use.type.o:
              #NOT IMPL.      description: Can use toggle gates.
              sg.use.type.q:
                description: Can use silent gates.
              sg.use.type.p:
                description: Can use private gates.
              sg.use.type.r:
                description: Can use random gates.
              sg.use.type.s:
                description: Can use force-shown gates.
              #NOT IMPL.    sg.use.type.t:
              #NOT IMPL.      description: Can use terminal gates.
              sg.use.type.u:
                description: Can use legacy bungee gates.
              #NOT IMPL.    sg.use.type.v:
              #NOT IMPL.      description: Can use gates with invisible signs.
              sg.use.type.fixed:
                description: Can use gates with a specified destination.
              sg.use.type.networked:
                description: Can use gates without a specified destination (networked gates).
          sg.use.design:
            description: Can use any portal, regardless of its portal's design (gatefile).
            children:
              sg.use.design.nether: true
              sg.use.design.water: true
              sg.use.design.wool: true
              sg.use.design.end: true
              #sg.use.design.<NAME> is a sub-node that allows for portals of a specific gate file design to be used.
          sg.use.owned:
            default: true
            description: Can use any owned portal.
          sg.use.server:
            description: Can use portals on specified server
            #sg.use.server.<NAME> is a sub-node that allows for portal connections to be established to specific servers

      sg.create:
        default: op
        description: Can create any portal.
        children:
          sg.create.world:
            default: true
            description: Can create portals in any dimension.
          #sg.create.world.<NAME> is a sub-node that allows for portals to be created in a specific dimension.
          sg.create.network:
            description: Can create portals on any network.
            children:
              sg.create.network.custom:
                description: Create portal on any custom network.
              #sg.create.network.custom.<NAME> is a sub-node that allows for portals to be created on a specific (specified) custom network.
              sg.create.network.personal:
                default: true
                children:
                  sg.create.network.personal.own:
                    default: true
                    description: Can create portals if they are on one's personal (username) network.
                  sg.create.network.personal.other:
                    default: op
                    description: Can create portals if they are on anothers personal (username) network.
              sg.create.network.default:
                description: Can create portals if they are on the default (central) network.
          sg.create.type:
            description: Can use all flags when creating portals
            children:
              sg.create.type.a:
                description: Can create gates with the always-on flag.
              sg.create.type.b:
                description: Can create gates with the backwards-facing flag.
              sg.create.type.f:
                description: Can create gates with the free flag.
              sg.create.type.h:
                description: Can create gates with the hidden flag.
              sg.create.type.i:
                description: Can create gates with the modern inter-server flag.
              sg.create.type.n:
                description: Can create gates with the hidden-network flag.
              #NOT IMPL.    sg.create.type.o:
              #NOT IMPL.      description: Can create gates with the toggle flag.
              sg.create.type.p:
                description: Can create gates with the private flag.
              sg.create.type.q:
                description: Can create silent gates.
              sg.create.type.r:
                description: Can create gates with the random flag.
              sg.create.type.s:
                description: Can create gates with the force-shown flag.
              #NOT IMPL.    sg.create.type.t:
              #NOT IMPL.      description: Can create terminal portals (be they in the terminal, or connecting to it)
              #NOT IMPL.      children:
              #NOT IMPL.        sg.create.type.t.new:
              #NOT IMPL.          description: Can create (sell) a new terminal gate on any network they have access to.
              #NOT IMPL.          children:
              #NOT IMPL.            sg.create.type.t.new.default:
              #NOT IMPL.              description: Can create (sell) a new terminal gate on the default terminal network.
              #NOT IMPL.        sg.create.type.t.connect:
              #NOT IMPL.          description: Can create a gate connecting to any existing, available (for sale) terminal gate. !!(BYPASSES stargate.create.network)!!
              #NOT IMPL.          children:
              #NOT IMPL.            sg.create.type.t.connect.default:
              #NOT IMPL.              description: Can create a gate connecting to any existing, available (for sale) terminal gate on the default network.              
              sg.create.type.u:
                description: Can create gates with the legacy bungee flag.
          #NOT IMPL.    sg.create.type.v:
          #NOT IMPL.      description: Can create gates with invisible signs.
          sg.create.design:
            default: true
            description: Can create any portal, regardless of the design (gatefile)
            children:
              #sg.use.design.<NAME>.gate is a sub-node that allows for portals of a specific gate file design to be created.
              sg.create.design.nether: true
              sg.create.design.water: true
              sg.create.design.wool: true
              sg.create.design.end: true


      sg.destroy:
        description: Can destroy any portal.
        default: op
        children:
          sg.destroy.world:
            description: Can destroy portals, regardless of dimension
            default: true
          #sg.destroy.world.<NAME> is a sub-node that allows for portals in a specific dimension to be destroyed.
          sg.destroy.network:
            description: Can destroy portals, regardless of network
            children:
              sg.destroy.network.personal:
                children:
                  sg.destroy.network.personal.own:
                    default: true
                    description: Can destroy any portals on your personal network
                  sg.destroy.network.personal.other:
                    default: op
                    description: Can destroy any portals on others personal network.
              sg.destroy.network.default:
                description: Can destroy any portals on the default network. (central)
              sg.destroy.network.custom:
                description: Can destroy any portals on any custom network.
          sg.destroy.type:
            description: Can destroy portals, regardless of type.
            children:
              sg.destroy.type.a:
                description: Can destroy always-on gates.
              sg.destroy.type.b:
                description: Can destroy backwards-facing gates.
              sg.destroy.type.f:
                description: Can destroy free gates.
              sg.destroy.type.h:
                description: Can destroy hidden gates.
              sg.destroy.type.i:
                description: Can destroy modern inter-server gates.
              sg.destroy.type.n:
                description: Can destroy hidden-network gates.
              #NOT IMPL.    sg.destroy.type.o:
              #NOT IMPL.      description: Can destroy toggle gates.
              sg.destroy.type.p:
                description: Can destroy private gates.
              sg.destroy.type.q:
                description: Can destroy silent gates.
              sg.destroy.type.r:
                description: Can destroy random gates.
              sg.destroy.type.s:
                description: Can destroy force-shown gates.
              #Not          sg.destroy.type.t:
              #NOT IMPL.      description: Can destroy terminal gates.
              sg.destroy.type.u:
                description: Can destroy legacy bungee gates.
          #NOT IMPL.    sg.destroy.type.v:
          #NOT IMPL.      description: Can destroy gates with invisible signs.
          sg.destroy.design:
            default: true
            description: Can destroy portals, regardless of design (gatefile).
            children:
              #sg.destroy.design.<NAME> is a sub-node that allows for portals of a specific gate file design to be destroyed.
              sg.destroy.design.nether: true
              sg.destroy.design.water: true
              sg.destroy.design.wool: true
              sg.destroy.design.end: true
          sg.destroy.owned:
            default: true
            description: Can destroy any owned portal.

      sg.preset:
        description: Premade groupings for convenience.
        children:
          sg.preset.user:
            description: A permission set intended to be given to players who will be using -- but not making -- stargates.
            children:
              sg.info: true
              sg.use: true
          sg.preset.gatemaker:
            description: A permission set intended to be given to players who will be making basic stargates for personal usage.
            children:
              sg.create.network.personal.own: true
              sg.destroy.network.personal.own: true
              sg.create.type.h: true
              sg.create.type.p: true
              sg.destroy.type.h: true
              sg.destroy.type.p: true
              sg.create.design: true
              sg.destroy.design: true
              sg.use.owned: true
              sg.destroy.owned: true
          #NOT IMPL.    sg.create.type.o: true
          #NOT IMPL.    sg.destroy.type.o: true
          #NOT IMPL.sg.preset.terminaluser:
          #NOT IMPL.  description: A permission set intended to be given to players who may wish to connect to an already-made terminal.
          #NOT IMPL.  children:
          #NOT IMPL.    sg.preset.gatemaker: true
          #NOT IMPL.    sg.create.type.t.connect.default: true
          #NOT IMPL.sg.preset.terminalmaker:
          #NOT IMPL.  description: A permission set intended to be given to any staff who will be involved in making / administrating a terminal system in spawn.
          #NOT IMPL.  children:
          #NOT IMPL.    sg.preset.terminaluser: true
          #NOT IMPL.    sg.preset.type.t.new.default: true
          sg.preset.builder:
            description: A set of permissions intended to be given to staff who will be making advanced stargates for server usage.
            children:
              sg.preset.gatemaker: true
              sg.create.network.custom: true
              sg.create.network.default: true
              sg.create.type.a: true
              sg.create.type.b: true
              sg.create.type.n: true
              sg.create.type.u: true
              sg.create.type.q: true
              sg.create.type.i: true
              sg.create.type.s: true
              #NOT IMPL.    sg.create.type.v: true
              sg.destroy.type.a: true
              sg.destroy.type.b: true
              sg.destroy.type.n: true
              sg.destroy.type.u: true
              sg.destroy.type.q: true
              sg.destroy.type.i: true
              sg.destroy.type.s: true
          #NOT IMPL.    sg.destroy.type.v: true
          sg.preset.moderator:
            description: A set of permissions intended to be given to staff who will be moderating stargate usage amongst players.
            children:
              sg.preset.builder: true
              sg.create.type.f: true
              sg.create.type.r: true
              sg.destroy.type.f: true
              sg.destroy.type.r: true
              sg.destroy.network: true
              sg.create.network: true
              sg.admin.bypass: true
              sg.destroy.type.s: true
              sg.create.type.s: true
          sg.preset.admin:
            description: A set of permissions intended to be given to admins tasked with configuring stargate and its permissions.
            children:
              sg.preset.moderator: true
              sg.create: true
              sg.destroy: true
              sg.admin: true
              sg.create.network.personal.other: true
              sg.destroy.network.personal.other: true
